### ISSUE TITLE
Handling InputRate & InputDialState

### ISSUE THREAD

**Issue by d-kr** [Kronzky/InfiniSaver#2]
While browsing the `save.dat` I found that there are Information about the input rate of each save slot. Maybe that information should to be backed up, too:

For example:

```
InputRate.4-5.0 = 9
InputRate.4-5.1 = 20
```

`InputDialState`is missing too, its the toogle from the sandbox levels.

**Comment by Kronzky** [comment]
Since both of those setting can be easily set via a couple of keystrokes, I don't think it worth the work to add it to the script.
